export const ACTION_ADD_VIEWED_PRODUCT = "catalog.ACTION_ADD_VIEWED_PRODUCT";
export const ACTION_TOGGLE_SHOW_ONLY_VIEWED = "catalog.ACTION_TOGGLE_SHOW_ONLY_VIEWED";
export const ACTION_ADD_VIEWED_CATEGORY = "catalog.ACTION_ADD_VIEWED_CATEGORY";
export const ACTION_SET_SCROLLED_PRODUCTS = "catalog.ACTION_SET_SCROLLED_PRODUCTS";
