query allProducts(
  $categoryId: Int
  $withDiscountOnly: Boolean
  $filters: String
  $sorting: String
  $offset: Int
  $first: Int
) {
  allProducts(
    categoryId: $categoryId
    withDiscountOnly: $withDiscountOnly
    filters: $filters
    sorting: $sorting
    offset: $offset
    first: $first
  ) {
    found
    total
    sorting {
      icon
      name
      value
      isSelected
    }
    filters {
      id
      name
      isColor
      hasChecked
      help
      type
      icon
      iconColor
      resetUrl
      values {
        id
        name
        isChecked
        filterValue
        help
        count
        url
        value
      }
    }
    products {
      id
      name
      shortDescription
      brand {
        id
        name
      }
      category {
        id
        name
      }
      images(size: SM, withColorOnly: true, first: 5) {
        id
        src
        width
        height
        isTitle
        attributeValue {
          id
          name
          value
        }
      }
      subProducts {
        id
        article
        price
        oldPrice
        discount
      }
    }
  }
}
