query product($id: Int) {
  product(id: $id) {
    id
    name
    shortDescription
    description
    brand {
      id
      name
    }
    category {
      id
      name
    }
    images {
      id
      src
      width
      height
      colorValue
      colorName
      isTitle
    }
    subProducts {
      id
      article
      price
      oldPrice
      discount
      attributes {
        name
        values {
          id
          name
          value
          description
        }
      }
    }
    attributes {
      id
      name
      values {
        name
        description
      }
    }
  }
}
