export const ACTION_ENABLE_CATALOG = "layout.ACTION_ENABLE_CATALOG";
export const ACTION_DISABLE_CATALOG = "layout.ACTION_DISABLE_CATALOG";
export const ACTION_TOOTLE_CATALOG = "layout.TOOTLE_CATALOG";

export const ACTION_ENABLE_MENU = "layout.ACTION_ENABLE_MENU";
export const ACTION_DISABLE_MENU = "layout.ACTION_DISABLE_MENU";
export const ACTION_TOOTLE_MENU = "layout.TOOTLE_MENU";

export const ACTION_RESET = "layout.RESET";
