export const ACTION_SET_SUB_PRODUCT_ID = "product.ACTION_SET_SUB_PRODUCT_ID";
export const ACTION_SET_ATTRIBUTE_VALUE_IDS = "product.ACTION_SET_ATTRIBUTE_VALUE_IDS";
export const ACTION_RESET = "product.ACTION_RESET";
