export const ACTION_SELECT_SUB_PRODUCT = "product.ACTION_SELECT_SUB_PRODUCT";
export const ACTION_SELECT_COLOR = "product.ACTION_SELECT_COLOR";
export const ACTION_UNSELECT_ALL = "product.ACTION_UNSELECT_ALL";
